version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: prod
    image: castor_server:${CASTOR_SERVER_VERSION:-latest}
    restart: always
    env_file:
    - .env
    environment:
      CASTOR_SERVER_HOST: 0.0.0.0
